package constants

// configuration constants
const (
	// CfgGoatEndpoint represents string (address:port) of goat server endpoint
	CfgGoatEndpoint = "goat-endpoint"
	// CfgDirectoryPath represents path to directory with files generated by Goat
	CfgDirectoryPath = "dir-path"
	// CfgPrometheusEndpoint represents string (address:port) of Prometheus endpoint
	CfgPrometheusEndpoint = "prometheus-endpoint"
	// CfgDebug represents true for debug mode; false otherwise
	CfgDebug = "debug"
	// CfgLogPath represents path to log file
	CfgLogPath = "log-path"
)
