language: go

go:
- 1.12.x
- 1.13.x
- 1.14.x

sudo: false

env:
- GO111MODULE=on

before_script:
- go build .
- go install -i github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- golangci-lint run ./...
- go test ./... -v